=begin
#Unsent API

#API for Unsent.dev

The version of the OpenAPI document: 1.0.0
Contact: support@unsent.dev
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Unsent
  class CreateCampaign200Response < ApiModelBase
    attr_accessor :id

    attr_accessor :name

    attr_accessor :from

    attr_accessor :subject

    attr_accessor :preview_text

    attr_accessor :contact_book_id

    attr_accessor :html

    attr_accessor :content

    attr_accessor :status

    attr_accessor :scheduled_at

    attr_accessor :batch_size

    attr_accessor :batch_window_minutes

    attr_accessor :total

    attr_accessor :sent

    attr_accessor :delivered

    attr_accessor :opened

    attr_accessor :clicked

    attr_accessor :unsubscribed

    attr_accessor :bounced

    attr_accessor :hard_bounced

    attr_accessor :complained

    attr_accessor :reply_to

    attr_accessor :cc

    attr_accessor :bcc

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'from' => :'from',
        :'subject' => :'subject',
        :'preview_text' => :'previewText',
        :'contact_book_id' => :'contactBookId',
        :'html' => :'html',
        :'content' => :'content',
        :'status' => :'status',
        :'scheduled_at' => :'scheduledAt',
        :'batch_size' => :'batchSize',
        :'batch_window_minutes' => :'batchWindowMinutes',
        :'total' => :'total',
        :'sent' => :'sent',
        :'delivered' => :'delivered',
        :'opened' => :'opened',
        :'clicked' => :'clicked',
        :'unsubscribed' => :'unsubscribed',
        :'bounced' => :'bounced',
        :'hard_bounced' => :'hardBounced',
        :'complained' => :'complained',
        :'reply_to' => :'replyTo',
        :'cc' => :'cc',
        :'bcc' => :'bcc',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'from' => :'String',
        :'subject' => :'String',
        :'preview_text' => :'String',
        :'contact_book_id' => :'String',
        :'html' => :'String',
        :'content' => :'String',
        :'status' => :'String',
        :'scheduled_at' => :'Time',
        :'batch_size' => :'Integer',
        :'batch_window_minutes' => :'Integer',
        :'total' => :'Integer',
        :'sent' => :'Integer',
        :'delivered' => :'Integer',
        :'opened' => :'Integer',
        :'clicked' => :'Integer',
        :'unsubscribed' => :'Integer',
        :'bounced' => :'Integer',
        :'hard_bounced' => :'Integer',
        :'complained' => :'Integer',
        :'reply_to' => :'Array<String>',
        :'cc' => :'Array<String>',
        :'bcc' => :'Array<String>',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'preview_text',
        :'contact_book_id',
        :'html',
        :'content',
        :'scheduled_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unsent::CreateCampaign200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unsent::CreateCampaign200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'preview_text')
        self.preview_text = attributes[:'preview_text']
      else
        self.preview_text = nil
      end

      if attributes.key?(:'contact_book_id')
        self.contact_book_id = attributes[:'contact_book_id']
      else
        self.contact_book_id = nil
      end

      if attributes.key?(:'html')
        self.html = attributes[:'html']
      else
        self.html = nil
      end

      if attributes.key?(:'content')
        self.content = attributes[:'content']
      else
        self.content = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'scheduled_at')
        self.scheduled_at = attributes[:'scheduled_at']
      else
        self.scheduled_at = nil
      end

      if attributes.key?(:'batch_size')
        self.batch_size = attributes[:'batch_size']
      else
        self.batch_size = nil
      end

      if attributes.key?(:'batch_window_minutes')
        self.batch_window_minutes = attributes[:'batch_window_minutes']
      else
        self.batch_window_minutes = nil
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      else
        self.total = nil
      end

      if attributes.key?(:'sent')
        self.sent = attributes[:'sent']
      else
        self.sent = nil
      end

      if attributes.key?(:'delivered')
        self.delivered = attributes[:'delivered']
      else
        self.delivered = nil
      end

      if attributes.key?(:'opened')
        self.opened = attributes[:'opened']
      else
        self.opened = nil
      end

      if attributes.key?(:'clicked')
        self.clicked = attributes[:'clicked']
      else
        self.clicked = nil
      end

      if attributes.key?(:'unsubscribed')
        self.unsubscribed = attributes[:'unsubscribed']
      else
        self.unsubscribed = nil
      end

      if attributes.key?(:'bounced')
        self.bounced = attributes[:'bounced']
      else
        self.bounced = nil
      end

      if attributes.key?(:'hard_bounced')
        self.hard_bounced = attributes[:'hard_bounced']
      else
        self.hard_bounced = nil
      end

      if attributes.key?(:'complained')
        self.complained = attributes[:'complained']
      else
        self.complained = nil
      end

      if attributes.key?(:'reply_to')
        if (value = attributes[:'reply_to']).is_a?(Array)
          self.reply_to = value
        end
      else
        self.reply_to = nil
      end

      if attributes.key?(:'cc')
        if (value = attributes[:'cc']).is_a?(Array)
          self.cc = value
        end
      else
        self.cc = nil
      end

      if attributes.key?(:'bcc')
        if (value = attributes[:'bcc']).is_a?(Array)
          self.bcc = value
        end
      else
        self.bcc = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @batch_size.nil?
        invalid_properties.push('invalid value for "batch_size", batch_size cannot be nil.')
      end

      if @batch_window_minutes.nil?
        invalid_properties.push('invalid value for "batch_window_minutes", batch_window_minutes cannot be nil.')
      end

      if @total.nil?
        invalid_properties.push('invalid value for "total", total cannot be nil.')
      end

      if @sent.nil?
        invalid_properties.push('invalid value for "sent", sent cannot be nil.')
      end

      if @delivered.nil?
        invalid_properties.push('invalid value for "delivered", delivered cannot be nil.')
      end

      if @opened.nil?
        invalid_properties.push('invalid value for "opened", opened cannot be nil.')
      end

      if @clicked.nil?
        invalid_properties.push('invalid value for "clicked", clicked cannot be nil.')
      end

      if @unsubscribed.nil?
        invalid_properties.push('invalid value for "unsubscribed", unsubscribed cannot be nil.')
      end

      if @bounced.nil?
        invalid_properties.push('invalid value for "bounced", bounced cannot be nil.')
      end

      if @hard_bounced.nil?
        invalid_properties.push('invalid value for "hard_bounced", hard_bounced cannot be nil.')
      end

      if @complained.nil?
        invalid_properties.push('invalid value for "complained", complained cannot be nil.')
      end

      if @reply_to.nil?
        invalid_properties.push('invalid value for "reply_to", reply_to cannot be nil.')
      end

      if @cc.nil?
        invalid_properties.push('invalid value for "cc", cc cannot be nil.')
      end

      if @bcc.nil?
        invalid_properties.push('invalid value for "bcc", bcc cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @from.nil?
      return false if @subject.nil?
      return false if @status.nil?
      return false if @batch_size.nil?
      return false if @batch_window_minutes.nil?
      return false if @total.nil?
      return false if @sent.nil?
      return false if @delivered.nil?
      return false if @opened.nil?
      return false if @clicked.nil?
      return false if @unsubscribed.nil?
      return false if @bounced.nil?
      return false if @hard_bounced.nil?
      return false if @complained.nil?
      return false if @reply_to.nil?
      return false if @cc.nil?
      return false if @bcc.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] from Value to be assigned
    def from=(from)
      if from.nil?
        fail ArgumentError, 'from cannot be nil'
      end

      @from = from
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] batch_size Value to be assigned
    def batch_size=(batch_size)
      if batch_size.nil?
        fail ArgumentError, 'batch_size cannot be nil'
      end

      @batch_size = batch_size
    end

    # Custom attribute writer method with validation
    # @param [Object] batch_window_minutes Value to be assigned
    def batch_window_minutes=(batch_window_minutes)
      if batch_window_minutes.nil?
        fail ArgumentError, 'batch_window_minutes cannot be nil'
      end

      @batch_window_minutes = batch_window_minutes
    end

    # Custom attribute writer method with validation
    # @param [Object] total Value to be assigned
    def total=(total)
      if total.nil?
        fail ArgumentError, 'total cannot be nil'
      end

      @total = total
    end

    # Custom attribute writer method with validation
    # @param [Object] sent Value to be assigned
    def sent=(sent)
      if sent.nil?
        fail ArgumentError, 'sent cannot be nil'
      end

      @sent = sent
    end

    # Custom attribute writer method with validation
    # @param [Object] delivered Value to be assigned
    def delivered=(delivered)
      if delivered.nil?
        fail ArgumentError, 'delivered cannot be nil'
      end

      @delivered = delivered
    end

    # Custom attribute writer method with validation
    # @param [Object] opened Value to be assigned
    def opened=(opened)
      if opened.nil?
        fail ArgumentError, 'opened cannot be nil'
      end

      @opened = opened
    end

    # Custom attribute writer method with validation
    # @param [Object] clicked Value to be assigned
    def clicked=(clicked)
      if clicked.nil?
        fail ArgumentError, 'clicked cannot be nil'
      end

      @clicked = clicked
    end

    # Custom attribute writer method with validation
    # @param [Object] unsubscribed Value to be assigned
    def unsubscribed=(unsubscribed)
      if unsubscribed.nil?
        fail ArgumentError, 'unsubscribed cannot be nil'
      end

      @unsubscribed = unsubscribed
    end

    # Custom attribute writer method with validation
    # @param [Object] bounced Value to be assigned
    def bounced=(bounced)
      if bounced.nil?
        fail ArgumentError, 'bounced cannot be nil'
      end

      @bounced = bounced
    end

    # Custom attribute writer method with validation
    # @param [Object] hard_bounced Value to be assigned
    def hard_bounced=(hard_bounced)
      if hard_bounced.nil?
        fail ArgumentError, 'hard_bounced cannot be nil'
      end

      @hard_bounced = hard_bounced
    end

    # Custom attribute writer method with validation
    # @param [Object] complained Value to be assigned
    def complained=(complained)
      if complained.nil?
        fail ArgumentError, 'complained cannot be nil'
      end

      @complained = complained
    end

    # Custom attribute writer method with validation
    # @param [Object] reply_to Value to be assigned
    def reply_to=(reply_to)
      if reply_to.nil?
        fail ArgumentError, 'reply_to cannot be nil'
      end

      @reply_to = reply_to
    end

    # Custom attribute writer method with validation
    # @param [Object] cc Value to be assigned
    def cc=(cc)
      if cc.nil?
        fail ArgumentError, 'cc cannot be nil'
      end

      @cc = cc
    end

    # Custom attribute writer method with validation
    # @param [Object] bcc Value to be assigned
    def bcc=(bcc)
      if bcc.nil?
        fail ArgumentError, 'bcc cannot be nil'
      end

      @bcc = bcc
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          from == o.from &&
          subject == o.subject &&
          preview_text == o.preview_text &&
          contact_book_id == o.contact_book_id &&
          html == o.html &&
          content == o.content &&
          status == o.status &&
          scheduled_at == o.scheduled_at &&
          batch_size == o.batch_size &&
          batch_window_minutes == o.batch_window_minutes &&
          total == o.total &&
          sent == o.sent &&
          delivered == o.delivered &&
          opened == o.opened &&
          clicked == o.clicked &&
          unsubscribed == o.unsubscribed &&
          bounced == o.bounced &&
          hard_bounced == o.hard_bounced &&
          complained == o.complained &&
          reply_to == o.reply_to &&
          cc == o.cc &&
          bcc == o.bcc &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, from, subject, preview_text, contact_book_id, html, content, status, scheduled_at, batch_size, batch_window_minutes, total, sent, delivered, opened, clicked, unsubscribed, bounced, hard_bounced, complained, reply_to, cc, bcc, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
