=begin
#Unsent API

#API for Unsent.dev

The version of the OpenAPI document: 1.0.0
Contact: support@unsent.dev
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Unsent
  class CreateCampaignRequest < ApiModelBase
    attr_accessor :name

    attr_accessor :from

    attr_accessor :subject

    attr_accessor :preview_text

    attr_accessor :contact_book_id

    attr_accessor :content

    attr_accessor :html

    attr_accessor :reply_to

    attr_accessor :cc

    attr_accessor :bcc

    attr_accessor :send_now

    # Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
    attr_accessor :scheduled_at

    attr_accessor :batch_size

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'from' => :'from',
        :'subject' => :'subject',
        :'preview_text' => :'previewText',
        :'contact_book_id' => :'contactBookId',
        :'content' => :'content',
        :'html' => :'html',
        :'reply_to' => :'replyTo',
        :'cc' => :'cc',
        :'bcc' => :'bcc',
        :'send_now' => :'sendNow',
        :'scheduled_at' => :'scheduledAt',
        :'batch_size' => :'batchSize'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'from' => :'String',
        :'subject' => :'String',
        :'preview_text' => :'String',
        :'contact_book_id' => :'String',
        :'content' => :'String',
        :'html' => :'String',
        :'reply_to' => :'CreateCampaignRequestReplyTo',
        :'cc' => :'CreateCampaignRequestReplyTo',
        :'bcc' => :'CreateCampaignRequestReplyTo',
        :'send_now' => :'Boolean',
        :'scheduled_at' => :'String',
        :'batch_size' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unsent::CreateCampaignRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unsent::CreateCampaignRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'preview_text')
        self.preview_text = attributes[:'preview_text']
      end

      if attributes.key?(:'contact_book_id')
        self.contact_book_id = attributes[:'contact_book_id']
      else
        self.contact_book_id = nil
      end

      if attributes.key?(:'content')
        self.content = attributes[:'content']
      end

      if attributes.key?(:'html')
        self.html = attributes[:'html']
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      end

      if attributes.key?(:'cc')
        self.cc = attributes[:'cc']
      end

      if attributes.key?(:'bcc')
        self.bcc = attributes[:'bcc']
      end

      if attributes.key?(:'send_now')
        self.send_now = attributes[:'send_now']
      end

      if attributes.key?(:'scheduled_at')
        self.scheduled_at = attributes[:'scheduled_at']
      end

      if attributes.key?(:'batch_size')
        self.batch_size = attributes[:'batch_size']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @from.to_s.length < 1
        invalid_properties.push('invalid value for "from", the character length must be greater than or equal to 1.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if @subject.to_s.length < 1
        invalid_properties.push('invalid value for "subject", the character length must be greater than or equal to 1.')
      end

      if @contact_book_id.nil?
        invalid_properties.push('invalid value for "contact_book_id", contact_book_id cannot be nil.')
      end

      if @contact_book_id.to_s.length < 1
        invalid_properties.push('invalid value for "contact_book_id", the character length must be greater than or equal to 1.')
      end

      if !@content.nil? && @content.to_s.length < 1
        invalid_properties.push('invalid value for "content", the character length must be greater than or equal to 1.')
      end

      if !@html.nil? && @html.to_s.length < 1
        invalid_properties.push('invalid value for "html", the character length must be greater than or equal to 1.')
      end

      if !@batch_size.nil? && @batch_size > 100000
        invalid_properties.push('invalid value for "batch_size", must be smaller than or equal to 100000.')
      end

      if !@batch_size.nil? && @batch_size < 1
        invalid_properties.push('invalid value for "batch_size", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length < 1
      return false if @from.nil?
      return false if @from.to_s.length < 1
      return false if @subject.nil?
      return false if @subject.to_s.length < 1
      return false if @contact_book_id.nil?
      return false if @contact_book_id.to_s.length < 1
      return false if !@content.nil? && @content.to_s.length < 1
      return false if !@html.nil? && @html.to_s.length < 1
      return false if !@batch_size.nil? && @batch_size > 100000
      return false if !@batch_size.nil? && @batch_size < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] from Value to be assigned
    def from=(from)
      if from.nil?
        fail ArgumentError, 'from cannot be nil'
      end

      if from.to_s.length < 1
        fail ArgumentError, 'invalid value for "from", the character length must be greater than or equal to 1.'
      end

      @from = from
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      if subject.to_s.length < 1
        fail ArgumentError, 'invalid value for "subject", the character length must be greater than or equal to 1.'
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] contact_book_id Value to be assigned
    def contact_book_id=(contact_book_id)
      if contact_book_id.nil?
        fail ArgumentError, 'contact_book_id cannot be nil'
      end

      if contact_book_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "contact_book_id", the character length must be greater than or equal to 1.'
      end

      @contact_book_id = contact_book_id
    end

    # Custom attribute writer method with validation
    # @param [Object] content Value to be assigned
    def content=(content)
      if content.nil?
        fail ArgumentError, 'content cannot be nil'
      end

      if content.to_s.length < 1
        fail ArgumentError, 'invalid value for "content", the character length must be greater than or equal to 1.'
      end

      @content = content
    end

    # Custom attribute writer method with validation
    # @param [Object] html Value to be assigned
    def html=(html)
      if html.nil?
        fail ArgumentError, 'html cannot be nil'
      end

      if html.to_s.length < 1
        fail ArgumentError, 'invalid value for "html", the character length must be greater than or equal to 1.'
      end

      @html = html
    end

    # Custom attribute writer method with validation
    # @param [Object] batch_size Value to be assigned
    def batch_size=(batch_size)
      if batch_size.nil?
        fail ArgumentError, 'batch_size cannot be nil'
      end

      if batch_size > 100000
        fail ArgumentError, 'invalid value for "batch_size", must be smaller than or equal to 100000.'
      end

      if batch_size < 1
        fail ArgumentError, 'invalid value for "batch_size", must be greater than or equal to 1.'
      end

      @batch_size = batch_size
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          from == o.from &&
          subject == o.subject &&
          preview_text == o.preview_text &&
          contact_book_id == o.contact_book_id &&
          content == o.content &&
          html == o.html &&
          reply_to == o.reply_to &&
          cc == o.cc &&
          bcc == o.bcc &&
          send_now == o.send_now &&
          scheduled_at == o.scheduled_at &&
          batch_size == o.batch_size
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, from, subject, preview_text, contact_book_id, content, html, reply_to, cc, bcc, send_now, scheduled_at, batch_size].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
