=begin
#Unsent API

#API for Unsent.dev

The version of the OpenAPI document: 1.0.0
Contact: support@unsent.dev
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Unsent
  class GetDomains200ResponseInner < ApiModelBase
    # The ID of the domain
    attr_accessor :id

    # The name of the domain
    attr_accessor :name

    # The ID of the team
    attr_accessor :team_id

    # The status of the domain
    attr_accessor :status

    # The region of the domain
    attr_accessor :region

    # Whether click tracking is enabled
    attr_accessor :click_tracking

    # Whether open tracking is enabled
    attr_accessor :open_tracking

    # The public key of the domain
    attr_accessor :public_key

    # The DKIM status of the domain
    attr_accessor :dkim_status

    # The SPF details of the domain
    attr_accessor :spf_details

    # The creation date of the domain
    attr_accessor :created_at

    # The last update date of the domain
    attr_accessor :updated_at

    # Whether DMARC is added
    attr_accessor :dmarc_added

    # Whether the domain is verifying
    attr_accessor :is_verifying

    # The error message of the domain
    attr_accessor :error_message

    # The subdomain of the domain
    attr_accessor :subdomain

    # The verification error of the domain
    attr_accessor :verification_error

    # The last checked time of the domain
    attr_accessor :last_checked_time

    # The DNS records of the domain
    attr_accessor :dns_records

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'team_id' => :'teamId',
        :'status' => :'status',
        :'region' => :'region',
        :'click_tracking' => :'clickTracking',
        :'open_tracking' => :'openTracking',
        :'public_key' => :'publicKey',
        :'dkim_status' => :'dkimStatus',
        :'spf_details' => :'spfDetails',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'dmarc_added' => :'dmarcAdded',
        :'is_verifying' => :'isVerifying',
        :'error_message' => :'errorMessage',
        :'subdomain' => :'subdomain',
        :'verification_error' => :'verificationError',
        :'last_checked_time' => :'lastCheckedTime',
        :'dns_records' => :'dnsRecords'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'team_id' => :'String',
        :'status' => :'String',
        :'region' => :'String',
        :'click_tracking' => :'Boolean',
        :'open_tracking' => :'Boolean',
        :'public_key' => :'String',
        :'dkim_status' => :'String',
        :'spf_details' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'dmarc_added' => :'Boolean',
        :'is_verifying' => :'Boolean',
        :'error_message' => :'String',
        :'subdomain' => :'String',
        :'verification_error' => :'String',
        :'last_checked_time' => :'String',
        :'dns_records' => :'Array<GetDomains200ResponseInnerDnsRecordsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'dkim_status',
        :'spf_details',
        :'error_message',
        :'subdomain',
        :'verification_error',
        :'last_checked_time',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unsent::GetDomains200ResponseInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unsent::GetDomains200ResponseInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'team_id')
        self.team_id = attributes[:'team_id']
      else
        self.team_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      else
        self.region = 'us-east-1'
      end

      if attributes.key?(:'click_tracking')
        self.click_tracking = attributes[:'click_tracking']
      else
        self.click_tracking = false
      end

      if attributes.key?(:'open_tracking')
        self.open_tracking = attributes[:'open_tracking']
      else
        self.open_tracking = false
      end

      if attributes.key?(:'public_key')
        self.public_key = attributes[:'public_key']
      else
        self.public_key = nil
      end

      if attributes.key?(:'dkim_status')
        self.dkim_status = attributes[:'dkim_status']
      end

      if attributes.key?(:'spf_details')
        self.spf_details = attributes[:'spf_details']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'dmarc_added')
        self.dmarc_added = attributes[:'dmarc_added']
      else
        self.dmarc_added = false
      end

      if attributes.key?(:'is_verifying')
        self.is_verifying = attributes[:'is_verifying']
      else
        self.is_verifying = false
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'subdomain')
        self.subdomain = attributes[:'subdomain']
      end

      if attributes.key?(:'verification_error')
        self.verification_error = attributes[:'verification_error']
      end

      if attributes.key?(:'last_checked_time')
        self.last_checked_time = attributes[:'last_checked_time']
      end

      if attributes.key?(:'dns_records')
        if (value = attributes[:'dns_records']).is_a?(Array)
          self.dns_records = value
        end
      else
        self.dns_records = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @team_id.nil?
        invalid_properties.push('invalid value for "team_id", team_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @public_key.nil?
        invalid_properties.push('invalid value for "public_key", public_key cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @dns_records.nil?
        invalid_properties.push('invalid value for "dns_records", dns_records cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @team_id.nil?
      return false if @status.nil?
      return false if @public_key.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @dns_records.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] team_id Value to be assigned
    def team_id=(team_id)
      if team_id.nil?
        fail ArgumentError, 'team_id cannot be nil'
      end

      @team_id = team_id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] public_key Value to be assigned
    def public_key=(public_key)
      if public_key.nil?
        fail ArgumentError, 'public_key cannot be nil'
      end

      @public_key = public_key
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] dns_records Value to be assigned
    def dns_records=(dns_records)
      if dns_records.nil?
        fail ArgumentError, 'dns_records cannot be nil'
      end

      @dns_records = dns_records
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          team_id == o.team_id &&
          status == o.status &&
          region == o.region &&
          click_tracking == o.click_tracking &&
          open_tracking == o.open_tracking &&
          public_key == o.public_key &&
          dkim_status == o.dkim_status &&
          spf_details == o.spf_details &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          dmarc_added == o.dmarc_added &&
          is_verifying == o.is_verifying &&
          error_message == o.error_message &&
          subdomain == o.subdomain &&
          verification_error == o.verification_error &&
          last_checked_time == o.last_checked_time &&
          dns_records == o.dns_records
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, team_id, status, region, click_tracking, open_tracking, public_key, dkim_status, spf_details, created_at, updated_at, dmarc_added, is_verifying, error_message, subdomain, verification_error, last_checked_time, dns_records].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
