=begin
#Unsent API

#API for Unsent.dev

The version of the OpenAPI document: 1.0.0
Contact: support@unsent.dev
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Unsent
  class SendEmailRequest < ApiModelBase
    attr_accessor :to

    attr_accessor :from

    # Optional when templateId is provided
    attr_accessor :subject

    # ID of a template from the dashboard
    attr_accessor :template_id

    attr_accessor :variables

    attr_accessor :reply_to

    attr_accessor :cc

    attr_accessor :bcc

    attr_accessor :text

    attr_accessor :html

    # Custom headers to included with the emails
    attr_accessor :headers

    attr_accessor :attachments

    attr_accessor :scheduled_at

    attr_accessor :in_reply_to_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'to' => :'to',
        :'from' => :'from',
        :'subject' => :'subject',
        :'template_id' => :'templateId',
        :'variables' => :'variables',
        :'reply_to' => :'replyTo',
        :'cc' => :'cc',
        :'bcc' => :'bcc',
        :'text' => :'text',
        :'html' => :'html',
        :'headers' => :'headers',
        :'attachments' => :'attachments',
        :'scheduled_at' => :'scheduledAt',
        :'in_reply_to_id' => :'inReplyToId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'to' => :'SendEmailRequestTo',
        :'from' => :'String',
        :'subject' => :'String',
        :'template_id' => :'String',
        :'variables' => :'Hash<String, String>',
        :'reply_to' => :'SendEmailRequestTo',
        :'cc' => :'SendEmailRequestTo',
        :'bcc' => :'SendEmailRequestTo',
        :'text' => :'String',
        :'html' => :'String',
        :'headers' => :'Hash<String, String>',
        :'attachments' => :'Array<Object>',
        :'scheduled_at' => :'Time',
        :'in_reply_to_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'text',
        :'html',
        :'in_reply_to_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unsent::SendEmailRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unsent::SendEmailRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      else
        self.to = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      end

      if attributes.key?(:'variables')
        if (value = attributes[:'variables']).is_a?(Hash)
          self.variables = value
        end
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      end

      if attributes.key?(:'cc')
        self.cc = attributes[:'cc']
      end

      if attributes.key?(:'bcc')
        self.bcc = attributes[:'bcc']
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      end

      if attributes.key?(:'html')
        self.html = attributes[:'html']
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      end

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'scheduled_at')
        self.scheduled_at = attributes[:'scheduled_at']
      end

      if attributes.key?(:'in_reply_to_id')
        self.in_reply_to_id = attributes[:'in_reply_to_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if !@subject.nil? && @subject.to_s.length < 1
        invalid_properties.push('invalid value for "subject", the character length must be greater than or equal to 1.')
      end

      if !@text.nil? && @text.to_s.length < 1
        invalid_properties.push('invalid value for "text", the character length must be greater than or equal to 1.')
      end

      if !@html.nil? && @html.to_s.length < 1
        invalid_properties.push('invalid value for "html", the character length must be greater than or equal to 1.')
      end

      if !@attachments.nil? && @attachments.length > 10
        invalid_properties.push('invalid value for "attachments", number of items must be less than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @to.nil?
      return false if @from.nil?
      return false if !@subject.nil? && @subject.to_s.length < 1
      return false if !@text.nil? && @text.to_s.length < 1
      return false if !@html.nil? && @html.to_s.length < 1
      return false if !@attachments.nil? && @attachments.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] to Value to be assigned
    def to=(to)
      if to.nil?
        fail ArgumentError, 'to cannot be nil'
      end

      @to = to
    end

    # Custom attribute writer method with validation
    # @param [Object] from Value to be assigned
    def from=(from)
      if from.nil?
        fail ArgumentError, 'from cannot be nil'
      end

      @from = from
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      if subject.to_s.length < 1
        fail ArgumentError, 'invalid value for "subject", the character length must be greater than or equal to 1.'
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] text Value to be assigned
    def text=(text)
      if !text.nil? && text.to_s.length < 1
        fail ArgumentError, 'invalid value for "text", the character length must be greater than or equal to 1.'
      end

      @text = text
    end

    # Custom attribute writer method with validation
    # @param [Object] html Value to be assigned
    def html=(html)
      if !html.nil? && html.to_s.length < 1
        fail ArgumentError, 'invalid value for "html", the character length must be greater than or equal to 1.'
      end

      @html = html
    end

    # Custom attribute writer method with validation
    # @param [Object] attachments Value to be assigned
    def attachments=(attachments)
      if attachments.nil?
        fail ArgumentError, 'attachments cannot be nil'
      end

      if attachments.length > 10
        fail ArgumentError, 'invalid value for "attachments", number of items must be less than or equal to 10.'
      end

      @attachments = attachments
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          to == o.to &&
          from == o.from &&
          subject == o.subject &&
          template_id == o.template_id &&
          variables == o.variables &&
          reply_to == o.reply_to &&
          cc == o.cc &&
          bcc == o.bcc &&
          text == o.text &&
          html == o.html &&
          headers == o.headers &&
          attachments == o.attachments &&
          scheduled_at == o.scheduled_at &&
          in_reply_to_id == o.in_reply_to_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [to, from, subject, template_id, variables, reply_to, cc, bcc, text, html, headers, attachments, scheduled_at, in_reply_to_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
